DATASET_ROOT: "../bdataset_stereo"
JSON_PATH: "train.json"
BATCH_SIZE: 2
IMAGE_SIZE: 256
WORKERS: 8
PIN_MEMORY: True
SHUFFLE: True

LEARNING_RATE: 0.0001
BETAS: [.9, .999]
EPS: 0.00000001
WEIGHT_DECAY: 0.0001

MILESTONES: [50, 100, 200]
GAMMA: .2

NUM_EPOCHS: 300
TEST: False
OUT_PATH: "./runs"
LOAD_MODEL: False
SAVE_MODEL: False
CHECKPOINT_FILE: "normal.pth"
